// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State__Update_639985b94e
    {
        private Mock<State<int>> _mockState;  // Changed from object to int as object is not a non-nullable value type

        [SetUp]
        public void Setup()
        {
            _mockState = new Mock<State<int>>();  // Changed from object to int as object is not a non-nullable value type
        }

        [Test]
        public void _Update_WhenCalled_CallsUpdateMethod()
        {
            // Arrange
            float deltaTime = 0.5f;

            // Act
            _mockState.Object._Update(deltaTime);

            // Assert
            _mockState.Verify(s => s._Update(deltaTime), Times.Once);
        }

        [Test]
        public void _Update_WithNegativeDeltaTime_ThrowsArgumentException()
        {
            // Arrange
            float deltaTime = -0.5f;

            // Act & Assert
            Assert.Throws<ArgumentException>(() => _mockState.Object._Update(deltaTime));
        }

        [TearDown]
        public void TearDown()
        {
            _mockState = null;
        }
    }
}
