// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using FiniteStateMachine; // Replace with correct namespace for FiniteStateMachine class

namespace YourNamespace.Tests
{
    [TestFixture]
    public class StateBaseTests
    {
        [Test]
        public void TestStateBase_StateBase_1()
        {
            // Arrange
            FiniteStateMachine fsm = new FiniteStateMachine();
            StateType stateKey = StateType.Initial;

            // Act
            StateBase state = new StateBase(fsm, stateKey);

            // Assert
            Assert.IsNotNull(state);
            Assert.AreEqual(fsm, state.FSM);
            Assert.AreEqual(stateKey, state.StateKey);
        }

        [Test]
        public void TestStateBase_StateBase_2()
        {
            // Arrange
            FiniteStateMachine fsm = new FiniteStateMachine();
            StateType stateKey = StateType.Final;

            // Act
            StateBase state = new StateBase(fsm, stateKey);

            // Assert
            Assert.IsNotNull(state);
            Assert.AreEqual(fsm, state.FSM);
            Assert.AreEqual(stateKey, state.StateKey);
        }
    }
}
