// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    public enum TestStateType // Define TestStateType
    {
        Start,
        End
        // Add other states as needed
    }

    public class FiniteStateChangeEventArgsTests
    {
        [Test]
        public void FiniteStateChangeEventArgs_ValidStateType_SetsRequestedType()
        {
            // Arrange
            var stateType = TestStateType.Start;

            // Act
            var eventArgs = new FiniteStateChangeEventArgs((StateType)stateType);

            // Assert
            Assert.AreEqual((StateType)stateType, eventArgs.RequestedType);
        }

        [Test]
        public void FiniteStateChangeEventArgs_NullStateType_ThrowsArgumentNullException()
        {
            // Arrange
            TestStateType? stateType = null; // Make stateType nullable

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(stateType.HasValue ? (StateType)stateType : throw new ArgumentNullException()));
        }
    }
}
