// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using Moq;

namespace FiniteStateMachine.Test
{
    public class State__End_5b00770643
    {
        public virtual void End()
        {
            // Define the behavior of the End method here
        }
    }

    public class State__End_5b00770643Tests
    {
        private Mock<State__End_5b00770643> _mockState;

        [SetUp]
        public void Setup()
        {
            _mockState = new Mock<State__End_5b00770643>();
        }

        [Test]
        public void _End_CallsEndMethod_Success()
        {
            // Arrange
            _mockState.Setup(m => m.End()).Verifiable();

            // Act
            _mockState.Object.End();

            // Assert
            _mockState.Verify(m => m.End(), Times.Once);
        }

        [Test]
        public void _End_CallsEndMethod_Failure()
        {
            // Arrange
            _mockState.Setup(m => m.End()).Throws(new System.Exception());

            // Act & Assert
            Assert.Throws<System.Exception>(() => _mockState.Object.End());
        }
    }
}
