// Test generated by RoostGPT for test test-csharp5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class FiniteStateBeganEventArgs_FiniteStateBeganEventArgs_9169a2778c
    {
        [Test]
        public void FiniteStateBeganEventArgs_ValidStateType_SetsTypeProperty()
        {
            // Arrange
            var expectedStateType = StateType.Valid; // Ensure 'Valid' is a valid enumeration in 'StateType'

            // Act
            var eventArgs = new FiniteStateBeganEventArgs(expectedStateType);

            // Assert
            Assert.AreEqual(expectedStateType, eventArgs.Type);
        }

        [Test]
        public void FiniteStateBeganEventArgs_InvalidStateType_ThrowsArgumentException()
        {
            // Arrange
            var invalidStateType = (StateType)100; // Ensure '100' is an invalid enumeration in 'StateType'

            // Act & Assert
            Assert.Throws<ArgumentException>(() => new FiniteStateBeganEventArgs(invalidStateType));
        }
    }
}
