// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;

namespace FiniteStateMachine.Test
{
    public class StateMachine_Initialize_99e1f35a6a
    {
        private StateMachine<int> _stateMachine; //Specify the type argument for the generic class StateMachine

        [SetUp]
        public void Setup()
        {
            _stateMachine = new StateMachine<int>(); //Specify the type argument for the generic class StateMachine
        }

        [Test]
        public void Initialize_StateMachineIsNotNull_Success()
        {
            _stateMachine.Initialize();

            Assert.IsNotNull(_stateMachine);
        }

        [Test]
        public void Initialize_StateMachineIsAlreadyInitialized_ThrowsException()
        {
            _stateMachine.Initialize();

            Assert.Throws<InvalidOperationException>(() => _stateMachine.Initialize());
        }

        [TearDown]
        public void Teardown()
        {
            _stateMachine = null;
        }
    }
}
