// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using System;

namespace StateMachine.Tests
{
    [TestFixture]
    public class StateTests
    {
        [Test]
        public void TestState_State_InitialStateSetCorrectly()
        {
            // Arrange
            StateMachine<int> stateMachine = new StateMachine<int>();
            int stateKey = 1;

            // Act
            State<int> state = new State<int>(stateMachine, stateKey);

            // Assert
            Assert.AreEqual(stateMachine, state.StateMachine);
            Assert.AreEqual(stateKey, state.StateKey);
        }

        [Test]
        public void TestState_State_MultipleStatesWithDifferentStateKeys()
        {
            // Arrange
            StateMachine<string> stateMachine = new StateMachine<string>();
            string stateKey1 = "State1";
            string stateKey2 = "State2";

            // Act
            State<string> state1 = new State<string>(stateMachine, stateKey1);
            State<string> state2 = new State<string>(stateMachine, stateKey2);

            // Assert
            Assert.AreEqual(stateMachine, state1.StateMachine);
            Assert.AreEqual(stateKey1, state1.StateKey);

            Assert.AreEqual(stateMachine, state2.StateMachine);
            Assert.AreEqual(stateKey2, state2.StateKey);
        }
    }
}
