// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateMachine_Update_73a5496b2c
    {
        private StateMachine<MockState> _stateMachine;
        private MockState _mockState;

        [SetUp]
        public void Setup()
        {
            _mockState = new MockState();
            _stateMachine = new StateMachine<MockState>(_mockState);
        }

        [Test]
        public void Update_WithCurrentState_InvokesUpdateOnState()
        {
            _stateMachine.Update(1.0f);

            Assert.IsTrue(_mockState.IsUpdateCalled);
        }

        [Test]
        public void Update_WithoutCurrentState_DoesNotThrowException()
        {
            _stateMachine.SetState(null);

            Assert.DoesNotThrow(() => _stateMachine.Update(1.0f));
        }
    }

    public class MockState : State<MockState>
    {
        public bool IsUpdateCalled { get; private set; }

        public override void Update(float deltaTime)
        {
            IsUpdateCalled = true;
        }

        public override void Begin(FiniteStateChangeEventArgs args, MockState state)
        {
            // Implementation here
        }

        public override void Load()
        {
            // Implementation here
        }

        public override void End()
        {
            // Implementation here
        }
    }
}
