// Test generated by RoostGPT for test test-csharp5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class StateMachine_Update_73a5496b2c
    {
        private StateMachine<int> _stateMachine; // Specify the generic type
        private Mock<State<int>> _mockState; // Specify the generic type

        [SetUp]
        public void Setup()
        {
            _mockState = new Mock<State<int>>(); // Specify the generic type
            _stateMachine = new StateMachine<int>(_mockState.Object); // Specify the generic type
        }

        [Test]
        public void Update_WithDeltaTime_StateUpdateInvoked()
        {
            // Arrange
            var deltaTime = 1f;

            // Act
            _stateMachine.Update(deltaTime);

            // Assert
            _mockState.Verify(s => s._Update(deltaTime), Times.Once);
        }

        [Test]
        public void Update_WithoutCurrentState_NoStateUpdateInvoked()
        {
            // Arrange
            var deltaTime = 1f;
            _stateMachine.m_currentState = null;

            // Act
            _stateMachine.Update(deltaTime);

            // Assert
            _mockState.Verify(s => s._Update(deltaTime), Times.Never);
        }
    }
}
