// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateMachine_FiniteStateMachine_4ac7eeddda
    {
        private FiniteStateMachine _finiteStateMachine;

        [SetUp]
        public void Setup()
        {
            _finiteStateMachine = new FiniteStateMachine();
        }

        [Test]
        public void FiniteStateMachine_WhenCalled_ShouldNotBeNull()
        {
            Assert.IsNotNull(_finiteStateMachine);
        }

        [Test]
        public void FiniteStateMachine_WhenCalled_ShouldBeOfTypeFiniteStateMachine()
        {
            Assert.IsInstanceOf<FiniteStateMachine>(_finiteStateMachine);
        }
    }
}
