// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System;
using NUnit.Framework;

namespace YourNamespace
{
    [TestFixture]
    public class FiniteStateMachineTests
    {
        [Test]
        public void TestFiniteStateMachine_ShouldCreateNewInstance()
        {
            // Arrange

            // Act
            var finiteStateMachine = new FiniteStateMachine();

            // Assert
            Assert.IsNotNull(finiteStateMachine);
        }

        [Test]
        public void TestFiniteStateMachine_ShouldInitializeInitialState()
        {
            // Arrange

            // Act
            var finiteStateMachine = new FiniteStateMachine();

            // Assert
            Assert.AreEqual("Initial", finiteStateMachine.CurrentState);
        }
    }

    public class FiniteStateMachine
    {
        public string CurrentState { get; set; }

        public FiniteStateMachine()
        {
            CurrentState = "Initial";
        }
    }
}
