// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    public enum StateType
    {
        Completed
    }

    public class FiniteStateEndedEventArgs : EventArgs
    {
        public StateType Type { get; private set; }

        public FiniteStateEndedEventArgs(StateType type)
        {
            Type = type;
        }
    }

    [TestFixture]
    public class FiniteStateEndedEventArgsTest
    {
        [Test]
        public void FiniteStateEndedEventArgs_WithValidStateType_SetsCorrectType()
        {
            // Arrange
            var stateType = StateType.Completed;

            // Act
            var eventArgs = new FiniteStateEndedEventArgs(stateType);

            // Assert
            Assert.AreEqual(stateType, eventArgs.Type);
        }

        [Test]
        public void FiniteStateEndedEventArgs_WithNullStateType_ThrowsArgumentNullException()
        {
            // Arrange
            StateType? stateType = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateEndedEventArgs(stateType.Value));
        }
    }
}
