// Test generated by RoostGPT for test test-csharp5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;
using System.Collections.Generic;

namespace FiniteStateMachine.Test
{
    public class StateMachine_AddState_95a50d88c6
    {
        private IStateMachine<int> _stateMachine;
        private IState<int> _state;

        [SetUp]
        public void Setup()
        {
            _stateMachine = new ConcreteStateMachine<int>();
            _state = _stateMachine.CreateState(1);
        }

        [Test]
        public void AddState_ValidState_AddsStateSuccessfully()
        {
            _stateMachine.AddState(_state);

            Assert.IsTrue(_stateMachine.ContainsState(1));
        }

        [Test]
        public void AddState_StateFromDifferentStateMachine_ThrowsException()
        {
            var differentStateMachine = new ConcreteStateMachine<int>();
            var differentState = differentStateMachine.CreateState(2);

            Assert.Throws<Exception>(() => _stateMachine.AddState(differentState));
        }

        [Test]
        public void AddState_NullState_ThrowsArgumentNullException()
        {
            IState<int> nullState = null;

            Assert.Throws<ArgumentNullException>(() => _stateMachine.AddState(nullState));
        }

        [Test]
        public void AddState_DuplicateState_ThrowsArgumentException()
        {
            _stateMachine.AddState(_state);

            Assert.Throws<ArgumentException>(() => _stateMachine.AddState(_state));
        }
    }
}
