// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateMachineTests
    {
        [Test]
        public void TestMoveTo_ValidStateKey_ReturnsStateKey()
        {
            // Arrange
            var stateMachine = new FiniteStateMachine<int>();
            var state1 = new State<int>(1);
            var state2 = new State<int>(2);
            stateMachine.AddState(state1);
            stateMachine.AddState(state2);
            
            // Act
            var result = stateMachine.MoveTo(2);
            
            // Assert
            Assert.AreEqual(2, result);
        }
        
        [Test]
        public void TestMoveTo_InvalidStateKey_ThrowsException()
        {
            // Arrange
            var stateMachine = new FiniteStateMachine<int>();
            var state1 = new State<int>(1);
            stateMachine.AddState(state1);
            
            // Act & Assert
            Assert.Throws<Exception>(() => stateMachine.MoveTo(2));
        }
    }
}
