// Test generated by RoostGPT for test test-cs using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using Moq;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State__Begin_bae0ee3e61
    {
        private Mock<State<string>> _mockState;
        private FiniteStateChangeEventArgs _eventArgs;
        private string _previousStateKey;

        [SetUp]
        public void Setup()
        {
            _mockState = new Mock<State<string>>();
            _eventArgs = new FiniteStateChangeEventArgs();
            _previousStateKey = "previousState";
        }

        [Test]
        public void Begin_StateIsCalled_ExpectedBehavior()
        {
            _mockState.Object.Begin(_eventArgs, _previousStateKey);
            _mockState.Verify(s => s.Begin(_eventArgs, _previousStateKey), Times.Once);
        }

        [Test]
        public void Begin_StateIsNotCalled_ExpectedBehavior()
        {
            _mockState.Verify(s => s.Begin(_eventArgs, _previousStateKey), Times.Never);
        }

        [Test]
        public void Begin_NullEventArgs_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => _mockState.Object.Begin(null, _previousStateKey));
        }

        [Test]
        public void Begin_NullPreviousStateKey_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => _mockState.Object.Begin(_eventArgs, null));
        }

        [TearDown]
        public void TearDown()
        {
            _mockState = null;
            _eventArgs = null;
            _previousStateKey = null;
        }
    }
}
