// Test generated by RoostGPT for test test-csharp5 using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    public enum StateType
    {
        Start,
        // Add other states as needed
    }

    public class StateInfo
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }

    public class FiniteStateChangeEventArgs : EventArgs
    {
        public StateType RequestedType { get; }
        public StateInfo StateInfo { get; }

        public FiniteStateChangeEventArgs(StateType requestedType, StateInfo stateInfo)
        {
            RequestedType = requestedType;
            StateInfo = stateInfo ?? throw new ArgumentNullException(nameof(stateInfo));
        }
    }

    [TestFixture]
    public class FiniteStateBeganEventArgs_FiniteStateChangeEventArgs_08e3fe74ea
    {
        [Test]
        public void Constructor_WithValidParameters_SetsPropertiesCorrectly()
        {
            // Arrange
            var requestedState = StateType.Start;
            var stateInfo = new StateInfo { Name = "Start", Description = "Start state" };

            // Act
            var args = new FiniteStateChangeEventArgs(requestedState, stateInfo);

            // Assert
            Assert.AreEqual(requestedState, args.RequestedType);
            Assert.AreEqual(stateInfo, args.StateInfo);
        }

        [Test]
        public void Constructor_WithNullStateInfo_ThrowsArgumentNullException()
        {
            // Arrange
            var requestedState = StateType.Start;
            StateInfo stateInfo = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(requestedState, stateInfo));
        }
    }
}
