// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;

namespace YourNamespace
{
    [TestFixture]
    public class YourTestClass
    {
        [Test]
        public void TestStateBase__End_5277dd1d57()
        {
            // TODO: Write your test code here

            // Arrange

            // Act

            // Assert

            // TODO: Add more test cases to cover all possible scenarios
        }
    }
}
